name: Build Collage Webpage

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-collage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Generate collage index.html
      run: |
        mkdir -p collage/images

          echo '<!DOCTYPE html>' > collage/index.html
          echo '<html lang="en">' >> collage/index.html
          echo '<head>' >> collage/index.html
          echo '  <meta charset="UTF-8">' >> collage/index.html
          echo '  <meta name="viewport" content="width=device-width, initial-scale=1.0">' >> collage/index.html
          echo '  <title>Image Collage</title>' >> collage/index.html
          echo '  <style>' >> collage/index.html
          echo '    body { font-family: sans-serif; text-align: center; background: #f4f4f4; padding: 2rem; }' >> collage/index.html
          echo '    .collage { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; max-width: 1000px; margin: auto; }' >> collage/index.html
          echo '    img { width: 100%; border-radius: 10px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }' >> collage/index.html
          echo '  </style>' >> collage/index.html
          echo '</head>' >> collage/index.html
          echo '<body>' >> collage/index.html
          echo '  <h1>Image Collage</h1>' >> collage/index.html
          echo '  <div class="collage">' >> collage/index.html

          for img in image-import/*.{jpg,jpeg,png,gif}; do
            [ -e "$img" ] || continue
            cp "$img" collage/images/
            echo "    <img src=\"images/$(basename "$img")\" alt=\"\">" >> collage/index.html
          done

          echo '  </div>' >> collage/index.html
          echo '</body>' >> collage/index.html
          echo '</html>' >> collage/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./collage
