name: Build Collage Webpage

on:
  push:
    branches: [main]

jobs:
  build-collage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Generate collage index.html
      run: |
        mkdir -p collage/images

        cat <<EOF > output/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Collage</title>
  <style>
    body { font-family: sans-serif; text-align: center; background: #f4f4f4; padding: 2rem; }
    .collage { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; max-width: 1000px; margin: auto; }
    img { width: 100%; border-radius: 10px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
  </style>
</head>
<body>
  <h1>Image Collage</h1>
  <div class="collage">
EOF

        for img in image-import/*.{jpg,jpeg,png,gif}; do
          [ -e "$img" ] || continue
          cp "$img" collage/images/
          echo "    <img src=\"images/$(basename "$img")\" alt=\"\">" >> collage/index.html
        done

        cat <<EOF >> collage/index.html
  </div>
</body>
</html>
EOF

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./collage
